# Generated by Django 3.0.3 on 2020-05-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_picture',
            field=models.ImageField(blank=True, default='default_product.jpg', null=True, upload_to='product_images'),
        ),
    ]
