# Generated by Django 3.0.3 on 2020-05-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_product_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='category',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Potential', 'Potential'), ('Regular', 'Regular')], max_length=50, null=True),
        ),
    ]
