# Generated by Django 3.0.3 on 2020-05-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Potential', 'Potential'), ('Discount', 'Discount'), ('Loyal', 'Loyal'), ('Impulsive', 'Impulsive')], max_length=50, null=True),
        ),
    ]
