# Generated by Django 3.0.3 on 2020-05-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200529_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='category',
            field=models.CharField(blank=True, choices=[(1, 'New'), (2, 'Impulsive'), (3, 'Discount'), (4, 'Loyal')], max_length=50, null=True),
        ),
    ]
