# Generated by Django 3.0.3 on 2020-05-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200529_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
