# Generated by Django 3.0.7 on 2020-06-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200630_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
